setup virtualenv for server. Fix issue #7
PiPot/pipot-server pull request #11
Opened 2019-03-02 04:32 UTC by VertexC

Set up virtualenv during server install. Currently set up env under /usr/src/pipot/activate. 

While it could be better to have a default name instead of letting user to input manually every time.

2019-03-04 18:37 UTC, canihavesomecoffee requested changes
This won't activate the venv when the daemon starts after a reboot, so this is gonna cause issues.

2019-03-08 20:08 UTC, canihavesomecoffee reviewed
Looks good, did you test this out? :)

2019-03-08 20:08 UTC, canihavesomecoffee approved these changes

2019-03-09 20:45 UTC, VertexC commented
Sure I did :).

2019-03-16 13:26 UTC, merged