add unittest TestAppBase, including setup the app and add the admin user for further test
PiPot/pipot-server pull request #26
Opened 2019-06-24 06:32 UTC by VertexC

(pipot-env) root@bowenc-MS-7A59:/usr/src/pipot/server/tests# python TestNestedMenus.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.067s

OK

2019-06-24 06:32 UTC, pep8speaks commented
Hello @VertexC, thank you for submitting this PR!

* In the file [`tests/TestAppBase.py`](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py):

> [Line 10:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 12:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 15:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L15): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 16:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L16): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 55:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L55): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 56:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L56): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 71:79](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L71): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 72:17](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L72): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 77:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L77): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 83:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L83): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 97:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L97): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 103:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L103): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 110:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L110): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 113:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L113): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 114:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L114): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 115:20](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestAppBase.py#L115): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/TestBase.py`](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py):

> [Line 10:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 12:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 15:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L15): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 16:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L16): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 55:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L55): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 56:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L56): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 71:79](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L71): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 72:17](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L72): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 77:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L77): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 83:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L83): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 97:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L97): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 103:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L103): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 110:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L110): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 113:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L113): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 114:1](https://github.com/PiPot/pipot-server/blob/0a135eb10907c9bde0348c6e42a6a41b1bbd8d3c/tests/TestBase.py#L114): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 115:20](ht [...]

2019-06-25 08:33 UTC, canihavesomecoffee commented
@pep8speaks suggest diff

2019-06-25 08:34 UTC, pep8speaks commented
Here you go with [the gist](https://gist.github.com/51a9c948ef0877dd2fbda870753a84ee) !

> You can ask me to create a PR against this branch with those fixes. Simply comment `@pep8speaks pep8ify`.

 @canihavesomecoffee @VertexC

2019-06-25 08:36 UTC, canihavesomecoffee requested changes
Can you add a .travis.yml file so I can enable Travis?

2019-06-26 07:59 UTC, VertexC commented
Open a new PR for the feature. #27

2019-06-26 07:59 UTC, closed without merging